site:
    root: ../atalanta-site

data-sources:
    atalanta-texts-orig: 
        type:   filesystem
        directory: ../atalanta-data/transcriptions/original-transcription
        filemask: '*.xml'

    atalanta-texts-english:
        type:   filesystem
        directory: ../atalanta-data/transcriptions/english-translation
        filemask: '*.xml'
    
pages: 
    emblems:
        uri: /emblem{pagenum}
        template: ../atalanta-template/emblem.xsl #Path to the XSLT
        items: //data-sources/atalanta-texts-english/file
        perpage: 1

static-sources:
    emblem-css:
        source: ../atalanta-code/css
        target: assets/css

    emblem-js:
        source: ../atalanta-code/js
        target: assets/js

    icons:
        source: ../atalanta-media/assets/icons
        target: assets/icons

    audio:
        source: ../atalanta-media/audio
        target: media/audio

    images:
        source: ../atalanta-media/images
        target: media/images